DROP TABLE IF EXISTS VISITS CASCADE;

CREATE TABLE VISITS (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES USERS(id) ON DELETE CASCADE,
    spot_id INTEGER REFERENCES SPOTS(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    image_url TEXT,
    rating SMALLINT NOT NULL,
    description TEXT,
    time_stamp TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);