DROP TABLE IF EXISTS SAVES;

CREATE TABLE SAVES (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES USERS(id) ON DELETE CASCADE,
  spot_id INTEGER REFERENCES SPOTS(id) ON DELETE CASCADE
);

