DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES USERS(id) ON DELETE CASCADE,
    visit_id INTEGER REFERENCES VISIT(id) ON DELETE CASCADE,
    description TEXT NOT NULL
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);