DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES USERS(id) ON DELETE CASCADE,
    visit_id INTEGER REFERENCES VISITS(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);