DROP TABLE IF EXISTS VISIT_LABELS;

CREATE TABLE VISIT_LABELS (
    id SERIAL PRIMARY KEY NOT NULL,
    visit_id INTEGER REFERENCES VISITS(id) ON DELETE CASCADE,
    label_id INTEGER REFERENCES LABELS(id) ON DELETE CASCADE
);